#!/bin/sh

FG_RED='\033[31m'
BG_RED='\033[41m'
FG_GREEN='\033[32m'
BG_GREEN='\033[42m'
NC='\033[0m'

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "\nValidating PSR2:\n"

# Check for phpcs
which ./vendor/bin/phpcs &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "\t$BG_RED Please install PHPCS $NC"
  exit 1
fi

RULESET=./phpcs.xml

for FILE in $STAGED_FILES
do
  ./vendor/bin/phpcs --standard="$RULESET" --colors "$FILE"

  if [[ "$?" == 0 ]]; then
    echo "\t$FG_GREEN PSR2 Passed: $FILE $NC"
  else
    PASS=false
  fi
done

echo "\nPSR2 validation completed!\n"

if ! $PASS; then
  echo "$BG_RED COMMIT FAILED: $NC Your commit contains files that should pass PSR2 but do not. Please fix the PSR2 errors and try again.\n"
  exit 1
else
  echo "$BG_GREEN COMMIT SUCCEEDED $NC \n"
fi

exit $?
